In [50]:
import pandas as pd

Load the merged dataset

In [51]:
df = pd.read_csv("/Users/ishik/Desktop/brooklyn99-sql-analytics/exports/b99_episodes_with_writer_director.csv")
df.head()

,Season,Episode,Title,Airdate,Rating,Total Votes,Episode Description,episode_category,is_holiday,Director_0,Director_1,Writer_0,Writer_1,Writer_2
0,1,1,Pilot,2014-01-16 00:00:00,7.8,4701,Detective Jake Peralta finds his work scrutini...,Great,Non-Holiday,Phil Lord,Christopher Miller,Dan Goor,Michael Schur,NaN
1,1,2,The Tagger,2014-01-23 00:00:00,7.5,3833,"When Jake arrives late for work, Captain Holt ...",Great,Non-Holiday,Craig Zisk,NaN,Dan Goor,Michael Schur,Norm Hiscock
2,1,3,The Slump,2014-01-30 00:00:00,7.6,3591,"With a backlog of unsolved cases, Jake finds h...",Great,Non-Holiday,Julie Anne Robinson,NaN,Dan Goor,Michael Schur,Prentice Penny
3,1,4,M.E. Time,2014-02-06 00:00:00,7.7,3473,"Jake meets an attractive Medical Examiner, but...",Great,Non-Holiday,Troy Miller,NaN,Dan Goor,Michael Schur,Gil Ozeri
4,1,5,The Vulture,2014-02-13 00:00:00,8.0,3370,A detective from Major Crimes takes over Jake'...,Great,Non-Holiday,Jason Ensler,NaN,Dan Goor,Michael Schur,Laura McCreary

In [52]:
df.columns

Index(['Season', 'Episode', 'Title', 'Airdate', 'Rating', 'Total Votes',
       'Episode Description', 'episode_category', 'is_holiday', 'Director_0',
       'Director_1', 'Writer_0', 'Writer_1', 'Writer_2'],
      dtype='object')

Average rating and total episodes per first credited director

In [53]:
director_stats = df.groupby("Director_0").agg(avg_rating =("Rating","mean"),total_episodes=("Rating","count")).sort_values("avg_rating",ascending=False)
director_stats

                      avg_rating  total_episodes
Director_0
Dan Goor                9.040000               5
Julian Farino           8.800000               1
Rebecca Asher           8.720000               5
Kyra Sedgwick           8.700000               1
Jamie Babbit            8.600000               2
Phil Traill             8.600000               1
Ryan Case               8.600000               2
Phil Augusta Jackson    8.500000               1
Michael Engler          8.500000               1
Payman Benz             8.450000               4
Matthew Nodella         8.325000               4
Akiva Schaffer          8.300000               2
Tim Kirkby              8.300000               1
Claire Scanlon          8.260000              10
Michael McDonald        8.258333              12
Dean Holland            8.257143               7
Giovani Lampassi        8.233333               3
Nisha Ganatra           8.200000               3
Jorma Taccone           8.200000               1
Jake Szymanski          8.200000               1
Tristram Shapeero       8.140000               5
Michael Schur           8.100000               2
Fred Goss               8.100000               2
Michael Spiller         8.100000               1
Peter Lauer             8.100000               1
Eric Appel              8.100000               4
Rebecca Addelman        8.100000               1
Thembi Banks            8.100000               1
Ken Whittingham         8.050000               2
Alex Reid               8.033333               3
Linda Mendoza           8.022222               9
Kat Coiro               8.000000               1
Max Winkler             8.000000               2
Gail Mancuso            8.000000               1
Jason Ensler            8.000000               1
Victor Nelli Jr.        7.983333               6
Beth McCarthy-Miller    7.966667               6
Maggie Carey            7.950000               4
Trent O'Donnell         7.933333               3
Luke Del Tredici        7.900000               3
Jaime Eliezer Karas     7.900000               1
Joe Lo Truglio          7.900000               1
Neil Campbell           7.900000               1
Kevin Bray              7.900000               1
Julie Anne Robinson     7.900000               2
Craig Zisk              7.860000               5
Daniella Eisman         7.800000               1
Phil Lord               7.800000               1
Kim O. Nguyen           7.800000               1
Troy Miller             7.700000               1
Tucker Gates            7.700000               1
Jaffar Mahmood          7.700000               2
Bruce McCulloch         7.600000               1
Jennifer Arnold         7.600000               1
Michael Blieden         7.600000               1
Cortney Carrillo        7.540000               5
Stephanie Beatriz       7.000000               1
Melissa Fumero          6.400000               1

Consider the first credited directors that have directed more than 3 episodes

In [54]:
director_stats[director_stats["total_episodes"] > 3].sort_values("total_episodes",ascending=False)

                      avg_rating  total_episodes
Director_0
Michael McDonald        8.258333              12
Claire Scanlon          8.260000              10
Linda Mendoza           8.022222               9
Dean Holland            8.257143               7
Victor Nelli Jr.        7.983333               6
Beth McCarthy-Miller    7.966667               6
Dan Goor                9.040000               5
Cortney Carrillo        7.540000               5
Craig Zisk              7.860000               5
Rebecca Asher           8.720000               5
Tristram Shapeero       8.140000               5
Matthew Nodella         8.325000               4
Payman Benz             8.450000               4
Eric Appel              8.100000               4
Maggie Carey            7.950000               4

Average rating and episodes per first credited writer

In [55]:
writer_stats = df.groupby("Writer_0").agg(avg_rating = ("Rating","mean"),total_episodes=("Rating","count")).sort_values("total_episodes",ascending=False)
writer_stats

                  avg_rating  total_episodes
Writer_0
Dan Goor            8.126207             145
David Phillips      8.050000               2
Marcy Jarreau       8.450000               2
Carol Kolb          8.500000               1
Evan Susser         7.800000               1
Laura McCreary      7.800000               1
Luke Del Tredici    8.200000               1

Count the total episodes directed by directors across all credits

In [56]:
all_directors = pd.concat([df['Director_0'], df['Director_1']], ignore_index=True).dropna()
all_directors.value_counts()

Michael McDonald        12
Claire Scanlon          10
Linda Mendoza            9
Dean Holland             7
Victor Nelli Jr.         6
Beth McCarthy-Miller     6
Tristram Shapeero        5
Rebecca Asher            5
Craig Zisk               5
Cortney Carrillo         5
Dan Goor                 5
Maggie Carey             4
Payman Benz              4
Eric Appel               4
Matthew Nodella          4
Trent O'Donnell          3
Nisha Ganatra            3
Alex Reid                3
Giovani Lampassi         3
Luke Del Tredici         3
Max Winkler              2
Ken Whittingham          2
Akiva Schaffer           2
Fred Goss                2
Ryan Case                2
Jamie Babbit             2
Julie Anne Robinson      2
Jaffar Mahmood           2
Michael Schur            2
Michael Blieden          1
Tucker Gates             1
Tim Kirkby               1
Jorma Taccone            1
Jake Szymanski           1
Julian Farino            1
Jason Ensler             1
Phil Lord                1
Troy Miller              1
Michael Engler           1
Peter Lauer              1
Michael Spiller          1
Phil Traill              1
Bruce McCulloch          1
Jaime Eliezer Karas      1
Kat Coiro                1
Jennifer Arnold          1
Phil Augusta Jackson     1
Stephanie Beatriz        1
Rebecca Addelman         1
Joe Lo Truglio           1
Melissa Fumero           1
Neil Campbell            1
Kim O. Nguyen            1
Kyra Sedgwick            1
Kevin Bray               1
Daniella Eisman          1
Gail Mancuso             1
Thembi Banks             1
 Christopher Miller      1
Name: count, dtype: int64

Count the total episodes writen by writers across all credits

In [57]:
all_writers = pd.concat((df["Writer_0"],df["Writer_1"],df["Writer_2"]),ignore_index=True).dropna()
all_writers.value_counts()

Dan Goor                     145
 Michael Schur               144
 Luke Del Tredici             17
 Justin Noble                  9
 Phil Augusta Jackson          9
 David Phillips                9
 Gabe Liedman                  7
 Laura McCreary                7
 Carly Hallam                  7
 Neil Campbell                 6
 Vanessa Ramos                 6
 Andrew Guest                  6
 Tricia McAlpin                6
 Carol Kolb                    6
 Lakshmi Sundaram              5
 Prentice Penny                5
 Gil Ozeri                     5
 Matt Lawton                   4
 Norm Hiscock                  4
 Matt O'Brien                  4
 Dewayne Perkins               3
 Lesley Arfin                  3
 Andy Gosche                   3
 Matt Murray                   3
 Lang Fisher                   3
 Brian Reich                   2
 Jessica Polonsky              2
 Paul Welsh                    2
 Jess Dweck                    2
 Marcy Jarreau                 2
 Van Robichaux                 2
David Phillips                 2
Marcy Jarreau                  2
Carol Kolb                     1
Laura McCreary                 1
Luke Del Tredici               1
Evan Susser                    1
 Alison Agosti                 1
 Kylie Condon                  1
 Brigitte Muñoz-Liebowitz      1
 David Quandt                  1
 Jeff Topolski                 1
 Aeysha Carr                   1
 Madeline Walter               1
 Nick Perdue                   1
 Evan Susser                   1
 Lamar Woods                   1
 Stephanie Amante-Ritter       1
 April Korto Quioh             1
Name: count, dtype: int64

Does episode category skew by first credited director?

In [58]:
pd.crosstab(df["Director_0"], df["episode_category"])

episode_category      Average  Great  Masterpiece  Weak
Director_0
Akiva Schaffer              0      1            1     0
Alex Reid                   0      3            0     0
Beth McCarthy-Miller        0      5            1     0
Bruce McCulloch             0      1            0     0
Claire Scanlon              1      5            4     0
Cortney Carrillo            0      3            1     1
Craig Zisk                  0      5            0     0
Dan Goor                    0      0            5     0
Daniella Eisman             0      1            0     0
Dean Holland                0      5            2     0
Eric Appel                  0      3            1     0
Fred Goss                   0      1            1     0
Gail Mancuso                0      1            0     0
Giovani Lampassi            0      2            1     0
Jaffar Mahmood              0      2            0     0
Jaime Eliezer Karas         0      1            0     0
Jake Szymanski              0      1            0     0
Jamie Babbit                0      1            1     0
Jason Ensler                0      1            0     0
Jennifer Arnold             0      1            0     0
Joe Lo Truglio              0      1            0     0
Jorma Taccone               0      1            0     0
Julian Farino               0      0            1     0
Julie Anne Robinson         0      2            0     0
Kat Coiro                   0      1            0     0
Ken Whittingham             0      2            0     0
Kevin Bray                  0      1            0     0
Kim O. Nguyen               0      1            0     0
Kyra Sedgwick               0      0            1     0
Linda Mendoza               0      8            1     0
Luke Del Tredici            0      3            0     0
Maggie Carey                1      1            2     0
Matthew Nodella             0      2            2     0
Max Winkler                 0      2            0     0
Melissa Fumero              1      0            0     0
Michael Blieden             0      1            0     0
Michael Engler              0      0            1     0
Michael McDonald            0      7            5     0
Michael Schur               0      2            0     0
Michael Spiller             0      1            0     0
Neil Campbell               0      1            0     0
Nisha Ganatra               0      2            1     0
Payman Benz                 0      1            3     0
Peter Lauer                 0      1            0     0
Phil Augusta Jackson        0      0            1     0
Phil Lord                   0      1            0     0
Phil Traill                 0      0            1     0
Rebecca Addelman            0      1            0     0
Rebecca Asher               0      1            4     0
Ryan Case                   0      0            2     0
Stephanie Beatriz           1      0            0     0
Thembi Banks                0      1            0     0
Tim Kirkby                  0      1            0     0
Trent O'Donnell             0      3            0     0
Tristram Shapeero           0      3            2     0
Troy Miller                 0      1            0     0
Tucker Gates                0      1            0     0
Victor Nelli Jr.            0      6            0     0

Dan goor has 5 episodes which were all masterpiece and courtney carrillo directed one episode which was weak

Does episode category skew by first credited director?

In [59]:
pd.crosstab(df["Writer_0"], df["episode_category"])

episode_category  Average  Great  Masterpiece  Weak
Writer_0
Carol Kolb              0      0            1     0
Dan Goor                4     98           42     1
David Phillips          0      2            0     0
Evan Susser             0      1            0     0
Laura McCreary          0      1            0     0
Luke Del Tredici        0      1            0     0
Marcy Jarreau           0      0            2     0

Dan goor is has an amazing record with 42 masterpieces and 98 great episodes. He has also written the most episodes.

Check out the top three directors by number of episodes

In [60]:
df[df["Director_0"] == 'Michael McDonald'][['Season','Episode','Airdate','Rating']].sort_values('Airdate')

     Season  Episode              Airdate  Rating
27        2        6  2014-11-09 00:00:00     8.2
42        2       21  2015-05-03 00:00:00     8.0
48        3        4  2016-01-14 00:00:00     8.5
49        3        5  2016-01-21 00:00:00     9.0
63        3       19  2016-04-28 00:00:00     7.7
68        4        1  2016-09-20 00:00:00     8.2
75        4        8  2016-11-29 00:00:00     7.8
86        4       19  2017-05-16 00:00:00     8.0
91        5        2  2017-10-03 00:00:00     8.4
117       6        6  2019-05-02 00:00:00     8.5
132       7        3  2020-02-13 00:00:00     8.6
137       7        8  2020-05-07 00:00:00     8.2

The ratings increased till sesason 3 ep 5. Then it went in a downward trajectory, but was consistent after season 4 episode 19.

In [61]:
df[df["Director_0"]=='Claire Scanlon'][['Season','Episode','Airdate','Rating']].sort_values('Airdate')

     Season  Episode              Airdate  Rating
37        2       16  2015-02-15 00:00:00     8.0
46        3        2  2016-01-07 00:00:00     7.7
60        3       16  2016-04-07 00:00:00     7.8
72        4        5  2016-10-18 00:00:00     8.8
103       5       14  2018-04-01 00:00:00     9.6
120       6        9  2019-05-30 00:00:00     8.1
134       7        5  2020-02-27 00:00:00     7.3
136       7        7  2020-03-12 00:00:00     8.7
145       8        3  2021-08-19 00:00:00     7.0
152       8       10  2021-09-16 00:00:00     9.6

The rating were more or less in an upward trajectory till Season 5 episode 14. 
Then ratings were more or less decreasing till the last episode season 8 episode 10.

In [62]:
df[df["Director_0"]=='Linda Mendoza'][['Season','Episode','Airdate','Rating']].sort_values('Airdate')

     Season  Episode              Airdate  Rating
28        2        7  2014-11-16 00:00:00     7.8
41        2       20  2015-04-26 00:00:00     7.7
50        3        6  2016-01-28 00:00:00     7.8
82        4       15  2017-04-25 00:00:00     8.3
97        5        8  2017-11-28 00:00:00     7.5
102       5       13  2018-03-25 00:00:00     8.3
121       6       10  2019-06-06 00:00:00     7.4
139       7       10  2020-04-02 00:00:00     8.0
151       8        9  2021-09-16 00:00:00     9.4

The ratings were more or less steady with the best episode coming in the end Season 8 episode 9